- README.md
- future_inverse_future.go
- future_inverse_future_test.go
- integrationtest/future-inverse-future/future_inverse_future_test.go
- integrationtest/future-inverse-future/testdata/futures-private-order-cancel-all.json
ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-cancelallactive
> feat: inverse future cancel all order

- client.go
- future_usdt_perpetual.go
It may have became necessary to include params related to authentication in the request body.
Somehow, this has worked with query strings in the past.
fix: https://github.com/hirokisan/bybit/issues/58
> fix: params for auth needed in request body

- future_usdt_perpetual.go
https://bybit-exchange.github.io/docs/futuresV2/linear/#t-placeactive
position_idx | false | integer | Position idx, used to identify positions in different position modes. Required if you are under One-Way Mode:0-One-Way Mode1-Buy side of both side mode2-Sell side of both side mode
-- | -- | -- | --
> Fix: Add 'position_idx' to CreateLinearOrderParam

- client_web_socket.go
- client_web_socket_service.go
- v5_account_service.go
- v5_asset_service.go
- v5_client_service.go
- v5_client_web_socket_service.go
- v5_execution_service.go
- v5_market_service.go
- v5_order_service.go
- v5_position_service.go
- v5_spot_leverage_token_service.go
- v5_spot_margin_trade_service.go
- v5_ws_inverse.go
- v5_ws_linear.go
- v5_ws_option.go
- v5_ws_private.go
- v5_ws_spot.go
docs(v5): https://bybit-exchange.github.io/docs/v5/upgrade-guide
> chore: prepare v5 template to implement

- README.md
- v5_client_web_socket_service.go
- v5_ws_private.go
- v5_ws_private_test.go
Implement Private V5 for Position.
It's inspired from the private V1 spot for outbound account info, but there are some some tweaks to get a better error handling when the connection is dead, in order to allow a reconnection (see README updates).
> Private Websocket Position V5

- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- go.mod
- go.sum
Because golangci/golangci-lint-action did not work with 1.19.
ref: https://github.com/hirokisan/bybit/actions/runs/4293459789/jobs/7481162398
```
run golangci-lint
Running [/home/runner/golangci-lint-1.46.2-linux-amd64/golangci-lint run --out-format=github-actions --disable-all --enable=errcheck,staticcheck,govet,unused,structcheck,gosimple] in [] ...
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x4b4
Error: golangci-lint exit with code 2
Ran golangci-lint in 11495ms
```
> go use 1.18 instead of 1.19

- v5_order_service.go
Unnamed struct makes it currently hard to aggregate open orders (linear and inverse or even between symbols / settle coins, as symbols or settle coins is a required param)
> Name struct on open orders

- client.go
- future_common.go
- future_inverse_perpetual.go
- future_usdt_perpetual.go
- integrationtest/future-inverse-future/future_inverse_future_test.go
- integrationtest/future-inverse-perpetual/future_inverse_perpetual_test.go
- integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go
Apply changes only in part.
for: https://github.com/hirokisan/bybit/issues/98
> fix: explicitly state that it is int64

- README.md
- integrationtest/v5/asset/asset_test.go
- integrationtest/v5/asset/testdata/v5-asset-get-withdrawal-records.json
- v5_asset_service.go
- v5_asset_service_test.go
- v5_enum.go
ref: https://bybit-exchange.github.io/docs/v5/asset/withdraw-record
for: https://github.com/hirokisan/bybit/issues/74#issuecomment-1508155493
> feat: v5 get withdrawal records

- v5_ws_private.go
- v5_ws_public.go
Surprised to find myself creating an update this soon 😢 
After opening the websocket for some time, I am getting `read tcp (my ip)->13.35.7.96:443: i/o timeout` error for every ping message sent. I tried adding the original `PingMessage` and the connection stabilised afterwards.
While comparing another bybit library written in Python, it seems they are sending both `PingMessage` and ping `TextMessage` as well.
ref: https://github.com/bybit-exchange/pybit/blob/9f3e32d4d771727b6e966cfd748b241ed48a1f6a/pybit/_websocket_stream.py#L236
Can you kindly have a look? Thanks.
> fix: update v5 wss public ping heartbeat 2

- v5_order_service.go
- v5_position_service.go
The error text should not start in upper case. Formality, but so as not to be annoyed by the illumination of the linter.
https://github.com/uber-go/guide/blob/master/style.md#errors
> fix linter issues

- client.go
- client_service.go
- time_service.go
- time_service_test.go
Example of a request problem when the local time is not synchronized:
```
10002, invalid request, please check your server timestamp or recv_window param. req_timestamp[1688721030939],server_timestamp[1688721231460],recv_window[5000]
```
Solution: added a service to get server time and a method to synchronize local and server time (delta detection).
> add sync server time service

- README.md
- integrationtest/v5/position/position_test.go
- integrationtest/v5/position/testdata/v5-position-set-risk-limit.json
- v5_position_service.go
- v5_position_service_test.go
ref: https://bybit-exchange.github.io/docs/v5/position/set-risk-limit
for: https://github.com/hirokisan/bybit/issues/74#issuecomment-1672462043
> feat: v5 set risk limit

- v5_market_service.go
This will allow us to use fields of corresponding types.
1. To pass them as arguments somewhere.
2. Simply because it is the best way to organize the structure.
> refactor: split `V5GetInstrumentsInfoSpotResult` struct

- client.go
Such a check would be more appropriate. It turns out that RetMsg may not have an "OK" even if the request succeeded and a result was obtained
> change server time response check

- integrationtest/v5/account/account_test.go
- v5_account_service.go
- v5_account_service_test.go
Found out that set-collateral-switch is not allowed to request for more than one coin at a time.
Also, for some reason test net does not send errors like main net does about changing USDT,USDC coins or trying to change more than coin at a time (e.g. "BTC,TRX"). Seems like there is no way to cover it with tests now. 
Should we do something with that?
> Fix set-collateral-switch account endpoint for REST API V5

- v5_market_service.go
Changes:
- extracted several unnamed structs into named structs (breaking change)
- renamed several structs for consistency (breaking change)
Reasoning:
- it's more convenient to work with named types: developers (like me) can create functions that receive or return values of type `V5GetInstrumentsInfoLinearInverseItem`, which is not possible for unnamed types
- `LotSizeFilterV5`/`PriceFilterV5` were renamed to `SpotLotSizeFilterV5`/`SpotPriceFilterV5` because they were used in spot responses; responses for other categories use different types
> refactor!(market): extract V5 market types

- client.go
Changes:
- status code 401 is mapped to ErrAccessDenied
- default branch returns error `fmt.Errorf("unexpected status code %d", resp.StatusCode)` instead of generic `errors.New("unexpected error")`
Reasoning:
- I had `unexpected error` errors and couldn't figure out why my key/secret pair wasn't working. Turns out I forgot to set address to point to Bybit testnet. Bybit returned status code 401 (my testnet key/secret were invalid for Bybit production environment). `unexpected error` without extra context isn't very helpful in similar cases.
> refactor(client): add context to access denied errors

- enum.go
- v5_order_service.go
Changes:
- added `MarketUnit` type and constants
- added `MarketUnit` field to `V5CreateOrderParam`
Reasoning:
- `marketUnit` is used to toggle between "quantity in base asset" (BTC in BTCUSDT) and "quantity in quote asset" (USDT in BTCUSDT) when creating spot orders. Defaults are not very intuitive in my opinion. It would be good to be able to change it when creating spot orders.
> feat(order): add marketUnit param to CreateOrder method

- client_web_socket.go
- logger.go
- v5_market_service.go
- v5_ws_private.go
- v5_ws_public.go
- ws_spot_v1_private.go
- ws_spot_v1_public_v1.go
- ws_spot_v1_public_v2.go
Changes:
- added interface `Logger`
- added global variable `logger`
- added method to change global logger
- replaced all `log` package references with `logger` global variable
- use noop logger by default
Reasoning:
- correct me if I'm wrong, current implementation prints debug data every time certain function is run. This simple PR disables all logging by default, but library users can supply their own logger and turn logging back on.
The solution isn't very flexible or configurable as I tried to keep it as simple as possible.
> fix: use noop logger by default

- client.go
- v5_account_service.go
Changes:
- fix set collateral coin depreciated post method usage
- add referer client field, which is used to set Referer request header for The Bybit Exchange Broker Program
Referer header and parameter description is kinda vague. I assume that referer value should be added to URL values before signing request, because there is an example:
> [Assume your Broker ID is "api.Abc" when placing orders. Order request should include "&referer=api.Abc&"](https://www.bybit.com/en/help-center/article/FAQ-API-Brokers-Program)
However, Support told me that X-Referer header has no deal with signing a request, which makes no sense to me, because then order requests might be spoofed by hackers in order to get additional rebates. Am I missing something?
Python library also does not include referer …
> Broker support

- v5_client_web_socket_service.go
- v5_ws_public.go
- v5_ws_public_ticker.go
This pull request addresses the need for adjustments due to changes in the structure of data updates from bybit's WebSocket service. Previously, certain columns such as `Bid1Price` and `Gamma` were included in updates, serving as indicators for categorizing data as linear, inverse, option, or spot. The omission of these columns in recent updates necessitated a new approach to ensure continued accurate categorization and processing.
- **Introduction of Category Field**: To facilitate precise processing and categorization of data updates, a category field has been added to the `V5WebsocketPublicService` and `V5WebsocketPublicTickerData` structures.
- **Implementation of Category-based Parsing**: The `UnmarshalJSON` function for data updates has been updated to utilize the newly introduced …
> Fix WebSocket data parsing to address omission of category indicators

- README.md
- v5_account_service.go
- v5_account_service_test.go
- v5_asset_service.go
- v5_asset_service_test.go
- v5_enum.go
- v5_ws_private_wallet.go
Changes to be made:
- fix: update UnifiedMarginStatus enums with relevant information;
- fix: disambiguate AccountType and AccountTypeV5 enums leaving only AccountTypeV5;
- fix: add missing ExecTypes;
- fix: README.md grammar typo;
- feature: add account type check on v5 account service GetWalletBalance endpoint;
- feature: provide ExecTypeV5 with detailed commentaries.
> Fix and refactor v5 enums

- README.md
- enum.go
- integrationtest/v5/account/account_test.go
- integrationtest/v5/account/testdata/v5-account-set-collateral-coin-batch.json
- v5_account_service.go
- v5_account_service_test.go
- implement POST /v5/account/set-collateral-switch-batch endpoint
- cover implemented endpoint with an integration test
- cover implemented endpoint with a mock test
- add MATIC and SOL coins to enums
- fix account integration test building failures
> feature: POST /v5/account/set-collateral-switch-batch

- v5_ws_public.go
Hi,
I would like to suggest adding a write deadline for the WebSocket.
When my app encounters network issues while attempting to write to the WebSocket, it gets stuck. A timeout feature would allow me to implement some restart procedures in those situations.
> WS write deadline for v5 public

- go.mod
- go.sum
- v5_ws_private.go
- v5_ws_public.go
- v5_ws_trade.go
- Addressing the issue where the WriteDeadline set at the beginning, as established in [PR #192](https://github.com/hirokisan/bybit/pull/192), caused all writes to fail with i/o timeout after 60 seconds.
- Example error: `write tcp 172.19.0.3:58072->13.33.88.14:443: i/o timeout`
- Modified to set WriteDeadline immediately before each WriteMessage to avoid timeout issues.
- Adjusted control messages like Ping, Pong, and Close to use WriteControl, as required.
- Ref: [websocket.Conn.WriteControl](https://pkg.go.dev/github.com/gorilla/websocket#Conn.WriteControl)
- Additionally updated gorilla/websocket to the latest version, v1.5.3.
> Fix i/o timeout in WebSocket writes by adjusting WriteDeadline and control message handling

- v5_ws_public.go
- v5_ws_public_ticker.go
Referring to:
https://bybit-exchange.github.io/docs/v5/ws/connect#public-channel---args-limits
You can pass several arguments to subscribe to several tickers at once in one ws connection. This allows you to save connections and not run into limits.
> feat: add v5 public SubscribeTickers

- client_web_socket.go
- testhelper/server_websocket_test.go
- v5_client_web_socket_service.go
- v5_ws_private_order_test.go
- v5_ws_private_position_test.go
- ws_spot_v1.go
- ws_spot_v1_private_test.go
Support `WebSocketClient` to use `WithDialer` for passing a custom dialer config, such as handshake timeout and proxy settings. This would be similar to how the HTTP REST API client supports `WithHTTPClient` for using a custom HTTP client.
> feat: support custom websocket dialer

- v5_enum.go
- v5_market_service.go
- v5_market_service_test.go
This PR adds support for the `copyTrading` field in the `GetInstrumentsInfo` method of Bybit API V5. This field indicates whether an instrument supports copy trading functionality and for which account types.
Changes include:
- Added a new data type `CopyTradingSupport` with four possible values:
- `none` - Instrument does not support copy trading for either normal or UTA accounts
- `both` - Instrument supports copy trading for both account types
- `utaOnly` - Instrument supports copy trading only for UTA accounts
- `normalOnly` - Instrument supports copy trading only for normal accounts
- Added the `CopyTrading` field to the `V5GetInstrumentsInfoLinearInverseItem` structure
- Updated tests to verify the new field
According to Bybit API V5 documentation, the `copyTrading` field is …
> feat: add copyTrading field support for GetInstrumentsInfo API

- v5_enum.go
- v5_order_service.go
- v5_order_service_test.go
This PR adds support for the slippage tolerance parameters in the Bybit V5 API, allowing users to control acceptable price deviation when creating market orders.
- Added `SlippageToleranceType` enum in `v5_enum.go` with `TickSize` and `Percent` values
- Added `SlippageToleranceType` and `SlippageTolerance` fields to the `V5CreateOrderParam` structure
- Added these same fields to the `V5GetOrder` structure for response parsing
- Created tests to verify order creation with slippage tolerance parameters
Slippage tolerance parameters are essential for traders in volatile markets to control how much price deviation they're willing to accept when executing market orders. This helps prevent orders from executing at unexpected prices during high volatility periods.
```go
// Creating a market …
```
> Add slippage tolerance parameters support for market orders

- v5_market_service.go
- v5_market_service_test.go
Add missing MarginTrading field to V5GetInstrumentsInfoSpotItem struct to match Bybit API specification. This field indicates margin trading support status for spot symbols.
for: https://github.com/hirokisan/bybit/issues/205
> feat: add marginTrading field support for GetInstrumentsInfo API (#205)
