README.md

Clearly state the implementation status for each API.

docs: tidy readme

---

account.go
account_spot.go
account_spot_test.go
go.mod
go.sum
market.go
market_spot.go

use github.com/google/go-querystring/query

refactor: param to url.Values

---

account_spot_test.go
account_test.go
client.go
testhelper/server.go
testhelper/server_test.go

ref: https://github.com/hirokisan/bybit/issues/10

test: client test for CI

---

client.go
client_test.go
response.go
testhelper/server.go

handle
- status code
- rate limit error
ref: https://github.com/hirokisan/bybit/issues/17

handle error response

---

README.md
integrationtest/spot-v1/spot_v1_test.go
integrationtest/spot-v1/testdata/spot-v1-open-orders.json
spot_v1.go
spot_v1_test.go

ref: https://bybit-exchange.github.io/docs/spot/v1/#t-openorders

feat: spot v1 open orders

---

README.md
integrationtest/spot-v1/spot_v1_test.go
integrationtest/spot-v1/testdata/spot-v1-get-wallet-balance.json
integrationtest/testhelper/helper.go
spot_v1.go
spot_v1_test.go

ref: https://bybit-exchange.github.io/docs/spot/v1/#t-balance

feat: spot v1 get wallet balance

---

README.md
enum.go
future_usdt_perpetual.go
future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/testdata/private-linear-order-list.json

ref: https://bybit-exchange.github.io/docs/futuresV2/linear/#t-getactive

feat: future usdt perpetual get active order

---

client.go
client_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-perpetual/future_inverse_perpetual_test.go
integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go
integrationtest/spot-v1/spot_v1_test.go
response.go

ref: https://bybit-exchange.github.io/docs/futuresV2/linear/#t-errors

feat: handle response error by code

---

README.md
future_inverse_perpetual.go
future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/testdata/v2-private-order-cancel-all.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse/#t-cancelallactive

feat: Inverse perpetual order cancel all

---

README.md
enum.go
enum_future_common.go
future_inverse_perpetual.go
future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/testdata/v2-private-stop-order-list.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse/#t-getcond

feat: inverse perpetual stop order list

---

README.md
future_inverse_perpetual.go
future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/testdata/v2-private-stop-order-cancel-all.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse/#t-cancelallcond

feat: inverse perpetual stop order cancel all

---

README.md
future_inverse_perpetual.go
future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/future_inverse_perpetual_test.go
integrationtest/future-inverse-perpetual/testdata/v2-private-stop-order.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse/#t-querycond

feat: inverse perpetual stop order query

---

README.md
future_usdt_perpetual.go
future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/testdata/private-linear-order-search.json

ref: https://bybit-exchange.github.io/docs/futuresV2/linear/#t-queryactive

feat: usdt perpetual query linear order

---

README.md
future_usdt_perpetual.go
future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/testdata/private-linear-stop-order-list.json

ref: https://bybit-exchange.github.io/docs/futuresV2/linear/#t-getcond

feat: usdt perpetual list linear stop order

---

README.md
future_usdt_perpetual.go
future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/testdata/private-linear-stop-order-cancel.json

ref: https://bybit-exchange.github.io/docs/futuresV2/linear/#t-cancelcond

feat: usdt perpetual cancel linear stop order

---

README.md
future_usdt_perpetual.go
future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/testdata/private-linear-stop-order-search.json

ref: https://bybit-exchange.github.io/docs/futuresV2/linear/#t-querycond

feat: usdt perpetual query linear stop order

---

README.md
future_usdt_perpetual.go
future_usdt_perpetual_test.go
integrationtest/future-usdt-perpetual/future_usdt_perpetual_test.go

ref: https://bybit-exchange.github.io/docs/futuresV2/linear/#t-tradingstop

feat: usdt perpetual linear trading stop

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-order-list.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-getactive

feat: inverse future order list

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-order-cancel.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-cancelactive

feat: inverse future cancel order

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-order.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-queryactive

feat: inverse future query order

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-stop-order-list.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-getcond

feat: inverse future list stop order

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-stop-order-cancel.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-cancelcond

feat: inverse future cancel stop order

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-stop-order-cancel-all.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-cancelallcond

feat: inverse future cancell all stop order

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-stop-order.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-querycond

feat: inverse future query stop order

---

README.md
future_inverse_future.go
future_inverse_future_test.go
integrationtest/future-inverse-future/future_inverse_future_test.go
integrationtest/future-inverse-future/testdata/futures-private-position-list.json

ref: https://bybit-exchange.github.io/docs/futuresV2/inverse_futures/#t-myposition

feat: inverse future position list

---

spot_v1.go

ref: https://bybit-exchange.github.io/docs/spot/v1/#t-querykline

fix: response params type became different

---

client.go
testclient.go

ref: https://github.com/hirokisan/bybit/issues/61

feat: enable to switch endpoints

---

README.md
derivative_common.go
derivative_common_test.go
derivative_contract.go
derivative_unified_margin.go
enum_derivative_common.go
integrationtest/derivative-contract/derivative_contract_test.go
integrationtest/derivative-contract/testdata/derivatives-public-instruments-info-for-option.json
integrationtest/derivative-contract/testdata/derivatives-public-instruments-info.json
integrationtest/derivative-unified-margin/derivative_unified_margin_test.go
integrationtest/derivative-unified-margin/testdata/derivatives-public-instruments-info-for-option.json
integrationtest/derivative-unified-margin/testdata/derivatives-public-instruments-info.json
testhelper/helper.go

ref: https://bybit-exchange.github.io/docs/derivativesV3/unified_margin/#t-dv_instrhead

feat: derivative common instruments info

---

client.go
client_test.go
future_usdt_perpetual_test.go

fix: https://github.com/hirokisan/bybit/issues/70

fix(client): handle response before unmarshal json

---

future_common.go
future_inverse_perpetual_test.go
integrationtest/future-inverse-future/testdata/v2-private-api-key-info.json
integrationtest/future-inverse-perpetual/testdata/v2-private-api-key-info.json
integrationtest/future-usdt-perpetual/testdata/v2-private-api-key-info.json

ref(impl): https://github.com/hirokisan/bybit/pull/71

test: /v2/private/account/api-key

---

response.go
v5_client_service.go

- response checking for all V5 services (`checkV5ResponseBody`)
- `CommonV5Response` struct

feat(v5): add common v5 response and response checking

---

README.md

docs: add `golang` tags into codeblocks

---

README.md
integrationtest/v5/account/Makefile
integrationtest/v5/account/wallet_balance_test.go
integrationtest/v5/user/Makefile
integrationtest/v5/user/api_key_test.go
v5_account_service.go
v5_account_service_test.go
v5_client_service.go
v5_enum.go
v5_user_service.go
v5_user_service_test.go

Implements methods for the following endpoints:
- GetWalletBalance - `/v5/account/wallet-balance`
- GetAPIKeyInfo - `/v5/user/query-api`

feat(v5): Add `/v5/account/wallet-balance` and `/v5/user/query-api` endpoints

---

README.md
integrationtest/v5/market/market_test.go
integrationtest/v5/market/testdata/v5-market-get-instruments-info-inverse.json
integrationtest/v5/market/testdata/v5-market-get-instruments-info-option.json
integrationtest/v5/market/testdata/v5-market-get-instruments-info-spot.json
v5_enum.go
v5_market_service.go
v5_market_service_test.go

docs: https://bybit-exchange.github.io/docs/v5/market/instrument

feat: v5 market instruments info

---

v5_client_web_socket_service.go
v5_ws_private.go
v5_ws_private_order.go
v5_ws_private_order_test.go

adding ws order
I've also added a SetPongHandler and ReadDeadline to really break the connection when a ping is failing (after 60s), instead of waiting on real data to do so

feat: v5 ws private order 

---

README.md
v5_position_service.go
v5_position_service_test.go

https://bybit-exchange.github.io/docs/v5/position/leverage

V5 Set Leverage

---

v5_ws_private.go

Current ping was not sending [proper instructions](https://bybit-exchange.github.io/docs/v5/ws/connect#how-to-send-the-heartbeat-packet) to Bybit server. A disconnection was happening every ~10 minutes. This fixes it.

Websocket: Fix Ping

---

README.md
v5_market_service.go
v5_market_service_test.go

https://bybit-exchange.github.io/docs/v5/market/tickers

V5 Tickers

---

README.md
integrationtest-ws/v5/public_test.go
integrationtest-ws/v5/testdata/piublic-v5-kline.json
v5_client_web_socket_service.go
v5_ws_public.go
v5_ws_public_kline.go
v5_ws_public_kline_test.go
v5_ws_public_orderbook.go

ref: https://bybit-exchange.github.io/docs/v5/websocket/public/kline

feat: v5 websocket public kline supports

---

v5_ws_public.go
v5_ws_public_kline.go
v5_ws_public_orderbook.go

ref: https://github.com/hirokisan/bybit/issues/104
Apply the changes to the public side.

v5 ws public: corresponding to concurrency

---

README.md
integrationtest/v5/market/market_test.go
integrationtest/v5/market/testdata/v5-market-get-funding-rate-history.json
v5_market_service.go
v5_market_service_test.go

ref: https://bybit-exchange.github.io/docs/v5/market/history-fund-rate

feat: v5 get funding rate history

---

README.md
integrationtest/v5/market/market_test.go
integrationtest/v5/market/testdata/v5-market-get-public-trading-history.json
v5_market_service.go
v5_market_service_test.go

ref: https://bybit-exchange.github.io/docs/v5/market/recent-trade

feat: v5 get public trading history

---

README.md
integrationtest/v5/order/order_test.go
integrationtest/v5/order/testdata/v5-amend-order.json
v5_order_service.go
v5_order_service_test.go

ref: https://bybit-exchange.github.io/docs/v5/order/amend-order

feat: v5 amend order

---

README.md
integrationtest/v5/position/position_test.go
integrationtest/v5/position/testdata/v5-position-get-closed-pnl.json
v5_enum.go
v5_position_service.go
v5_position_service_test.go

ref: https://bybit-exchange.github.io/docs/v5/position/close-pnl
for: https://github.com/hirokisan/bybit/issues/74#issuecomment-1497228323

feat: v5 get closed pnl

---

README.md
integrationtest/v5/asset/Makefile
integrationtest/v5/asset/asset_test.go
integrationtest/v5/asset/testdata/v5-asset-get-internal-transfer-records.json
v5_asset_service.go
v5_asset_service_test.go
v5_enum.go

ref: https://bybit-exchange.github.io/docs/v5/asset/inter-transfer-list
for: https://github.com/hirokisan/bybit/issues/74#issuecomment-1497228323

feat: v5 get internal transfer records

---

README.md
integrationtest/v5/account/account_test.go
integrationtest/v5/account/testdata/v5-account-get-transaction-log.json
v5_account_service.go
v5_account_service_test.go
v5_enum.go

ref: https://bybit-exchange.github.io/docs/v5/account/transaction-log

feat: v5 get transaction log

---

README.md
integrationtest/v5/asset/asset_test.go
integrationtest/v5/asset/testdata/v5-asset-get-internal-deposit-records.json
v5_asset_service.go
v5_asset_service_test.go
v5_enum.go

ref: https://bybit-exchange.github.io/docs/v5/asset/internal-deposit-record

feat: v5 get internal deposit records

---

README.md
integrationtest/v5/asset/asset_test.go
integrationtest/v5/asset/testdata/v5-asset-get-sub-deposit-records.json
v5_asset_service.go
v5_asset_service_test.go

ref: https://bybit-exchange.github.io/docs/v5/asset/sub-deposit-record
for: https://github.com/hirokisan/bybit/issues/74#issuecomment-1508155493

feat: v5 get sub deposit records

---

README.md
integrationtest/v5/market/market_test.go
integrationtest/v5/market/testdata/v5-market-get-risk-limit.json
v5_enum.go
v5_market_service.go
v5_market_service_test.go

ref: https://bybit-exchange.github.io/docs/v5/market/risk-limit
for: https://github.com/hirokisan/bybit/issues/74#issuecomment-1610296726

feat: v5 get risk limit

---

v5_account_service.go

I add fields that were missing from the structure.
https://bybit-exchange.github.io/docs/v5/account/wallet-balance#http-request

add `free` & `locked` v5 balance

---

v5_execution_service.go
v5_execution_service_test.go

I tried to add v5().Execution().GetExecutionList(params) method getting [/v5/execution/list](https://bybit-exchange.github.io/docs/v5/position/execution) endpoint data

added v5().Execution().GetExecutionList() method

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile

- use .golangci.yml
- add `make lint`

chore: use .golangci.yml

---

.github/workflows/golangci-lint.yml
.github/workflows/test.yml
go.mod

Upgrade go version from 1.18 to 1.21.

chore: upgrade to go 1.21

---

.golangci.yml
spot_v1.go
v5_asset_service.go
v5_execution_service.go
v5_order_service_test.go

- Add `revive` to .golangci.yml
- Change `fooId` to `fooID`.

fix: adapt to linter

---

v5_order_service.go

https://bybit-exchange.github.io/docs/v5/order/create-order#request-parameters

Add missing fields to V5CreateOrderParam

---

client.go
client_web_socket.go
logger.go
v5_market_service.go
v5_ws_private.go
v5_ws_public.go
ws_spot_v1_private.go
ws_spot_v1_public_v1.go
ws_spot_v1_public_v2.go

Changes to be made:
- introduce new default logger
- refactor global logger type to *log.Logger
- add independent logger and debug option for client
- refactor existing log messages to provide more information

Refactor logger

---

integrationtest/v5/market/testdata/v5-market-get-risk-limit.json
v5_market_service.go
v5_market_service_test.go

for: https://github.com/hirokisan/bybit/issues/175

feat: handle cursor on GetRiskLimit

---

integrationtest-ws/v5/private_test.go
integrationtest-ws/v5/testdata/private-v5-execution.json
v5_client_web_socket_service.go
v5_ws_private.go
v5_ws_private_execution.go

Added a subscription for order execution

add v5 ws execution

---

go.mod
v5_account_service.go
v5_client_web_socket_service.go
v5_ws_trade.go
v5_ws_trade_order.go

Simple implementation. Does not care whether the request is submitted successfully, the actual situation is based on the message received by order event.

support v5 ws trade

---

README.md
v5_account_service.go
v5_ws_trade.go
v5_ws_trade_order.go

for: https://github.com/hirokisan/bybit/pull/183

fix: /v5/account/fee-rate

---

v5_enum.go

https://bybit-exchange.github.io/docs/v5/enum#unifiedmarginstatus

feat: update unified margin status enums

---

v5_ws_public_liquidation.go
v5_ws_public_liquidation_test.go

Hi, response data now object.  
https://bybit-exchange.github.io/docs/v5/websocket/public/liquidation

Update websocket liquidation 

---

v5_position_service.go
v5_position_service_test.go

Issue: https://github.com/hirokisan/bybit/issues/190

added curren realised parameter to v5 position list service

---

v5_ws_private.go
v5_ws_trade.go

ref. https://github.com/hirokisan/bybit/pull/192

feat: v5 ws write deadline for private, trade

---

.github/workflows/golangci-lint.yml
.github/workflows/test.yml
.golangci.yml
go.mod
response.go

upgrade versions such as go.mod, golangci-lint.yml, test.yml.

chore: upgrade versions

---

v5_ws_public.go
v5_ws_public_kline.go

The idea is the same as in https://github.com/hirokisan/bybit/pull/195: add the ability to subscribe to several topics to use fewer websocket connections.

add v5 public `SubscribeKlines`

---

README.md
v5_client_web_socket_service.go
v5_ws_public.go
v5_ws_public_allliquidation.go
v5_ws_public_allliquidation_test.go

Added missing websocket functionality 
https://bybit-exchange.github.io/docs/v5/websocket/public/all-liquidation

feat: Add functionality to public.websocket.all-liquidation

---

v5_asset_service.go

Add transfer status to response struct. 
It exists in both internal transfer and universal transfer.
Refer:
- https://bybit-exchange.github.io/docs/v5/asset/transfer/unitransfer
- https://bybit-exchange.github.io/docs/v5/asset/transfer/create-inter-transfer

Add `Transfer` status
